### ISSUE TITLE
Can't get README example to work with 3.1.0 - URI: bad argument 

### ISSUE THREAD

**Issue by walquis** [timdorr/tesla-api#334]
Copy/pasted the example in README, filled in the creds, and got the error below.

Traceback (most recent call last):
	2: from test.rb:12:in `<main>'
	1: from ... /vendor/bundle/gems/tesla_api-3.1.0/lib/tesla_api/client.rb:113:in `login!'
/opt/local/ruby-2.6.5/lib/ruby/2.6.0/uri/common.rb:739:in `URI': bad argument (expected URI object or URI string) (ArgumentError)

**Comment by walquis** [comment]
Traced to account lockout.  Now getting a 400 from api.post in client.rb.  Will see if I can figure out what's unhappy there...
