### ISSUE TITLE
Tesla API went down , CAPTCHA installed.

### ISSUE THREAD

**Issue by fkhera** [timdorr/tesla-api#392]
Has anyone had issues with the Tesla API, our raspberry PI which just accesses the token , oauth API seems to have gone down.

Code used for REST API:
https://auth.tesla.com/oauth2/v3/authorize?code_challenge=Q9MaFZwd3Y0GQx1E42nGDn4NtnAhpgqh6l-BwdYe6Tg&client_id=ownerapi&state=tesla_exporter&redirect_uri=https%3A%2F%2Fauth.tesla.com%2Fvoid%2Fcallback&response_type=code&code_challenge_method=S256&scope=openid+email+offline_access

IT appears Tesla is using some type "code catchya" , any ideas how to get past that?
Following the link above shows a captchya.

Coming to non MFA flow:
Traceback (most recent call last):
  File "/home/pi/powerwallTimeOfUse.py", line 242, in authenticate
    code_url = resp.headers["location"]
  File "/usr/lib/python2.7/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
Traceback (most recent call last):
  File "/home/pi/powerwallTimeOfUse.py", line 67, in main
    tpw.productlist()

**Comment by fkhera** [comment]
A bit of a long shot but could use human solving service:
https://auth.tesla.com/oauth2/v1/authorize?client_id=teslaweb&response_type=code&scope=openid%20email%20profile&redirect_uri=https%3A//www.tesla.com/openid-connect/generic&state=_WDi4NXQGYV7yGOi9df-2qGznv9xzaUz2RUKEIo0dpU&locale=en-US

It appears the new API piece is:

_csrf: rPIvYAwz-131lLqcOXxNPeZmUP-BZzyiGB7k
_phase: authenticate
_process: 1
transaction_id: aQk9oHMs
cancel: 
identity: email
credential: pass
captcha: Pwab
