### ISSUE TITLE
Argument error at login!

### ISSUE THREAD

**Issue by Maquis90** [timdorr/tesla-api#440]
Hi, 
I get this error message when I try to load my program.
Does anyone have an idea why this happens?

```
pi@raspberrypi:~/waveshare-epaper-display $ ruby tesla-charge.rb                
/home/pi/.rbenv/versions/3.0.0/lib/ruby/3.0.0/uri/common.rb:676:in `URI': bad argument (expected URI object or URI string) (ArgumentError) 
from /home/pi/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/tesla_api-3.1.0/lib/tesla_api/client.rb:113:in `login!'
from tesla-charge.rb:5:in `<main>'
```

```
require 'tesla_api'
require 'json'

tesla_api = TeslaApi::Client.new(email: 'xxxx@xxxx', client_id: 'ownerapi', client_secret: 'c7257eb71a564034f9419ee651c7d0e5f7aa6bfbd18bafb5c5c033b093bb2fa3', retry_options: 3)
tesla_api.login!('xxxxxxxx')
```

**Comment by timdorr** [comment]
You're probably getting a CAPTCHA. We're tracking this in #431
